apiVersion: v1
kind: Endpoints
metadata:
  name: bioplatform
subsets:
  - addresses:
      - ip: 95.111.255.92
    ports:
      - port: 5569
---
apiVersion: v1
kind: Service
metadata:
  name: bioplatform
spec:
  ports:
    - protocol: TCP
      port: 5569
      targetPort: 5569
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bioplatform
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: labolatorium.mateuszwozniak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bioplatform
                port:
                  number: 5569