[project]
name = "bioplatform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "awsebcli>=3.23.2",
    "django>=4.2.20",
]
